#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

from collect_report import classify_error, summarize_run
from zhanfu_runtime import get_browser_list

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = Path(r"C:\Users\9400\Documents\zhanfu_collect_runs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

DEFAULT_STORES = [2515382, 2376919, 2273435, 2337386, 2276096, 2280875, 2264045, 2276389]


def run_subprocess(command: list[str], timeout: int) -> tuple[int, str, str]:
    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        check=False,
    )
    return result.returncode, result.stdout, result.stderr


def parse_store_ids(raw: str | None) -> list[int]:
    if not raw:
        return DEFAULT_STORES
    return [int(part.strip()) for part in raw.split(",") if part.strip()]


def save_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def append_progress(log_path: Path, event: dict) -> None:
    with log_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Stable multi-store collector for ZhanFu sales + FMCG diagnostics")
    parser.add_argument("--config", help="Path to JSON config file")
    parser.add_argument("--retry-config", help="Path to retry_config.json generated by a previous run")
    parser.add_argument("--stores", help="Comma-separated mall_id list. Default is curated stable order.")
    parser.add_argument("--sales-limit", type=int, default=1, help="How many stores to include in each sales batch")
    parser.add_argument("--skip-sales", action="store_true")
    parser.add_argument("--skip-fmcg-diagnose", action="store_true")
    parser.add_argument("--run-fmcg-order-lookup", action="store_true")
    parser.add_argument("--timeout-sales", type=int, default=240)
    parser.add_argument("--timeout-diagnose", type=int, default=180)
    parser.add_argument("--timeout-fmcg-order-lookup", type=int, default=300)
    parser.add_argument("--retry-failed-sales-batches", action="store_true")
    parser.add_argument("--retry-failed-batches-once", action="store_true")
    parser.add_argument("--sleep-between-batches-seconds", type=int, default=3)
    args = parser.parse_args()

    config = {}
    if args.retry_config:
        config = json.loads(Path(args.retry_config).read_text(encoding="utf-8"))
    elif args.config:
        config = json.loads(Path(args.config).read_text(encoding="utf-8"))

    stores = parse_store_ids(args.stores) if args.stores else config.get("stores") or DEFAULT_STORES
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = OUTPUT_DIR / f"run_{timestamp}"
    run_dir.mkdir(parents=True, exist_ok=True)

    available = {int(item.get("mall_id", 0)): item for item in get_browser_list()}
    skip_sales = args.skip_sales or bool(config.get("skip_sales", False))
    skip_fmcg_diagnose = args.skip_fmcg_diagnose or bool(config.get("skip_fmcg_diagnose", False))
    run_fmcg_order_lookup = args.run_fmcg_order_lookup or bool(config.get("run_fmcg_order_lookup", False))
    sales_limit = args.sales_limit if "--sales-limit" in sys.argv[1:] else int(config.get("sales_limit", 1))
    timeout_sales = args.timeout_sales if "--timeout-sales" in sys.argv[1:] else int(config.get("timeout_sales", 240))
    timeout_diagnose = args.timeout_diagnose if "--timeout-diagnose" in sys.argv[1:] else int(config.get("timeout_diagnose", 180))
    timeout_fmcg_order_lookup = args.timeout_fmcg_order_lookup if "--timeout-fmcg-order-lookup" in sys.argv[1:] else int(config.get("timeout_fmcg_order_lookup", 300))
    retry_failed_sales_batches = args.retry_failed_sales_batches or bool(config.get("retry_failed_sales_batches", False))
    retry_failed_batches_once = args.retry_failed_batches_once or bool(config.get("retry_failed_batches_once", False))
    sleep_between_batches_seconds = args.sleep_between_batches_seconds if "--sleep-between-batches-seconds" in sys.argv[1:] else int(config.get("sleep_between_batches_seconds", 3))

    progress_log = run_dir / "progress.jsonl"

    summary = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "config": {
            "stores": stores,
            "sales_limit": sales_limit,
            "skip_sales": skip_sales,
            "skip_fmcg_diagnose": skip_fmcg_diagnose,
            "run_fmcg_order_lookup": run_fmcg_order_lookup,
            "timeout_sales": timeout_sales,
            "timeout_diagnose": timeout_diagnose,
            "timeout_fmcg_order_lookup": timeout_fmcg_order_lookup,
            "retry_failed_sales_batches": retry_failed_sales_batches,
            "retry_failed_batches_once": retry_failed_batches_once,
            "sleep_between_batches_seconds": sleep_between_batches_seconds,
        },
        "stores_requested": stores,
        "stores_available": sorted([store_id for store_id in stores if store_id in available]),
        "sales_batches": [],
        "fmcg_diagnose": None,
        "fmcg_order_lookup": None,
        "fmcg_order_lookup_retry": None,
        "sales_retry_batches": [],
        "human_summary": {},
    }
    save_json(run_dir / "summary.json", summary)
    append_progress(progress_log, {"event": "run_started", "stores": stores, "ts": datetime.now().isoformat(timespec="seconds")})

    if not skip_fmcg_diagnose and 2376919 in stores:
        cmd = [sys.executable, str(SCRIPT_DIR / "fmcg_single_store_diagnose.py")]
        code, stdout, stderr = run_subprocess(cmd, timeout=timeout_diagnose)
        payload = {
            "command": cmd,
            "returncode": code,
            "stdout": stdout,
            "stderr": stderr,
            "error_type": None if code == 0 else classify_error(stdout, stderr),
        }
        summary["fmcg_diagnose"] = payload
        append_progress(progress_log, {"event": "fmcg_diagnose", "returncode": code, "error_type": payload.get("error_type"), "ts": datetime.now().isoformat(timespec="seconds")})
        save_json(run_dir / "fmcg_diagnose.json", payload)
        save_json(run_dir / "summary.json", summary)

    if run_fmcg_order_lookup:
        cmd = [
            sys.executable,
            str(SCRIPT_DIR / "collector_fmcg_orders.py"),
            "--input-csv",
            str(Path(r"C:\Users\9400\Documents\fmcg_negative_review_followup.csv")),
            "--output-dir",
            str(run_dir / "fmcg_orders"),
            "--flush-every",
            "1",
        ]
        code, stdout, stderr = run_subprocess(cmd, timeout=timeout_fmcg_order_lookup)
        payload = {
            "command": cmd,
            "returncode": code,
            "stdout": stdout,
            "stderr": stderr,
            "error_type": None if code == 0 else classify_error(stdout, stderr),
        }
        summary["fmcg_order_lookup"] = payload
        append_progress(progress_log, {"event": "fmcg_order_lookup", "returncode": code, "error_type": payload.get("error_type"), "ts": datetime.now().isoformat(timespec="seconds")})
        save_json(run_dir / "fmcg_order_lookup.json", payload)
        save_json(run_dir / "summary.json", summary)

    if not skip_sales:
        batch_size = max(1, sales_limit)
        for i in range(0, len(stores), batch_size):
            batch = stores[i : i + batch_size]
            append_progress(progress_log, {"event": "sales_batch_started", "batch": batch, "batch_index": i // batch_size + 1, "ts": datetime.now().isoformat(timespec="seconds")})
            if len(batch) != 1:
                raise RuntimeError("standard collector mode currently expects sales_limit=1 for per-store execution")
            store_id = batch[0]
            cmd = [
                sys.executable,
                str(SCRIPT_DIR / "collector_sales.py"),
                "--store-id",
                str(store_id),
                "--output-dir",
                str(run_dir / f"sales_store_{store_id}"),
                "--flush-every",
                "1",
            ]
            code, stdout, stderr = run_subprocess(cmd, timeout=timeout_sales)
            payload = {
                "batch": batch,
                "command": cmd,
                "returncode": code,
                "stdout": stdout,
                "stderr": stderr,
                "error_type": None if code == 0 else classify_error(stdout, stderr),
            }
            summary["sales_batches"].append(payload)
            for store_id in batch:
                store_payload = {
                    "store_id": store_id,
                    "batch": batch,
                    "command": cmd,
                    "returncode": code,
                    "stdout": stdout,
                    "stderr": stderr,
                    "error_type": payload.get("error_type"),
                }
                save_json(run_dir / f"store_{store_id}.json", store_payload)
            append_progress(progress_log, {"event": "sales_batch_finished", "batch": batch, "batch_index": i // batch_size + 1, "returncode": code, "error_type": payload.get("error_type"), "ts": datetime.now().isoformat(timespec="seconds")})
            save_json(run_dir / f"sales_batch_{i // batch_size + 1}.json", payload)
            save_json(run_dir / "summary.json", summary)
            time.sleep(sleep_between_batches_seconds)

        if retry_failed_sales_batches:
            if summary.get("fmcg_order_lookup") and summary["fmcg_order_lookup"].get("returncode") != 0:
                retry_cmd = summary["fmcg_order_lookup"]["command"]
                retry_payload = {"command": retry_cmd, "attempt": 2}
                if retry_failed_batches_once:
                    code, stdout, stderr = run_subprocess(retry_cmd, timeout=timeout_fmcg_order_lookup)
                    retry_payload.update({
                        "returncode": code,
                        "stdout": stdout,
                        "stderr": stderr,
                        "error_type": None if code == 0 else classify_error(stdout, stderr),
                    })
                summary["fmcg_order_lookup_retry"] = retry_payload
                append_progress(progress_log, {"event": "fmcg_order_lookup_retry", "returncode": retry_payload.get("returncode"), "error_type": retry_payload.get("error_type"), "ts": datetime.now().isoformat(timespec="seconds")})
                save_json(run_dir / "fmcg_order_lookup_retry.json", retry_payload)
                save_json(run_dir / "summary.json", summary)
                time.sleep(sleep_between_batches_seconds)

            failed_batches = [item for item in summary["sales_batches"] if item.get("returncode") != 0]
            for item in failed_batches:
                retry_cmd = item["command"]
                retry_payload = {
                    "batch": item["batch"],
                    "command": retry_cmd,
                    "attempt": 2,
                }
                if retry_failed_batches_once:
                    code, stdout, stderr = run_subprocess(retry_cmd, timeout=timeout_sales)
                    retry_payload.update({
                        "returncode": code,
                        "stdout": stdout,
                        "stderr": stderr,
                        "error_type": None if code == 0 else classify_error(stdout, stderr),
                    })
                summary["sales_retry_batches"].append(retry_payload)
                for store_id in item["batch"]:
                    store_retry_payload = {
                        "store_id": store_id,
                        "batch": item["batch"],
                        "command": retry_cmd,
                        "attempt": 2,
                        "returncode": retry_payload.get("returncode"),
                        "stdout": retry_payload.get("stdout", ""),
                        "stderr": retry_payload.get("stderr", ""),
                        "error_type": retry_payload.get("error_type"),
                    }
                    save_json(run_dir / f"store_{store_id}_retry.json", store_retry_payload)
                append_progress(progress_log, {"event": "sales_batch_retry", "batch": item["batch"], "returncode": retry_payload.get("returncode"), "error_type": retry_payload.get("error_type"), "ts": datetime.now().isoformat(timespec="seconds")})
                save_json(run_dir / f"sales_retry_batch_{'_'.join(str(x) for x in item['batch'])}.json", retry_payload)
                save_json(run_dir / "summary.json", summary)
                time.sleep(sleep_between_batches_seconds)

    summary["finished_at"] = datetime.now().isoformat(timespec="seconds")
    summary["human_summary"] = summarize_run(summary)
    failed_store_ids = []
    for item in summary.get("sales_batches", []):
        if item.get("returncode") != 0:
            failed_store_ids.extend(item.get("batch", []))
    retry_config = {
        "stores": sorted(set(failed_store_ids)),
        "sales_limit": summary["config"]["sales_limit"],
        "skip_sales": False,
        "skip_fmcg_diagnose": summary["config"]["skip_fmcg_diagnose"],
        "run_fmcg_order_lookup": bool(summary.get("fmcg_order_lookup") and summary["fmcg_order_lookup"].get("returncode") != 0),
        "timeout_sales": summary["config"]["timeout_sales"],
        "timeout_diagnose": summary["config"]["timeout_diagnose"],
        "timeout_fmcg_order_lookup": summary["config"]["timeout_fmcg_order_lookup"],
        "retry_failed_sales_batches": True,
        "retry_failed_batches_once": True,
        "sleep_between_batches_seconds": summary["config"]["sleep_between_batches_seconds"],
    }
    summary["retry_config_path"] = str(run_dir / "retry_config.json")
    save_json(run_dir / "retry_config.json", retry_config)
    save_json(run_dir / "summary.json", summary)
    (run_dir / "summary.txt").write_text(json.dumps(summary["human_summary"], ensure_ascii=False, indent=2), encoding="utf-8")
    append_progress(progress_log, {"event": "run_finished", "ts": datetime.now().isoformat(timespec="seconds"), "retry_config_path": str(run_dir / "retry_config.json")})
    index_path = OUTPUT_DIR / "runs_index.json"
    if index_path.exists():
        try:
            index_data = json.loads(index_path.read_text(encoding="utf-8"))
            if not isinstance(index_data, list):
                index_data = []
        except Exception:
            index_data = []
    else:
        index_data = []
    index_data.append({
        "run_dir": str(run_dir),
        "started_at": summary.get("started_at"),
        "finished_at": summary.get("finished_at"),
        "stores": summary.get("stores_requested", []),
        "summary_txt": str(run_dir / "summary.txt"),
        "retry_config": str(run_dir / "retry_config.json"),
        "human_summary": summary.get("human_summary", {}),
    })
    index_data = index_data[-50:]
    index_path.write_text(json.dumps(index_data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"status": "ok", "run_dir": str(run_dir), "runs_index": str(index_path)}, ensure_ascii=True))


if __name__ == "__main__":
    main()
